### ISSUE TITLE
Feature suggestion: Add project info

### ISSUE THREAD

**Issue by arnested** [grasmash/drupal-issue-chrome#2]
Would it be possible to render the project name of the issue as well?

That info could previously be spotted in the URL but is with your, otherwise very nice extension, now hidden more.

**Comment by grasmash** [comment]
Interesting request. As of 0.0.5, the following 3 formats are available in the extension options:

* #[node:nid]: [node:status] | [node:title]
* #[node:nid]: [node:title]
* #[node:nid]

Would you suggest adding a fourth one in the form of "[node:project] #[node:nid]: [node:status] | [node:title]" ?

**Comment by grasmash** [comment]
Unfortunately I'd need to make another web request to get the project name. Only the project nid is listed on the issue node. I'd rather not double the number of web requests, so I think this feature request will need to be rejected.

**Comment by arnested** [comment]
I agree.
