### ISSUE TITLE
Data loss with user-entered sites when testing different configuration options

### ISSUE THREAD

**Issue by anavarre** [grasmash/drupal-issue-chrome#3]
When configuring the extension, you have the below section:

> Allow this extension to read and change all your data on websites you visit:
>
> * On click
> * On specific sites
> * On all sites

If you select **On specific sites** and add a few sites, upon switching to any other option then all your previously-entered sites are lost. This isn't ideal from a UX perspective, because you expect to be able to test different options without losing data ever.

**Comment by grasmash** [comment]
Those options aren’t provided by this plugin. Maybe you’re you’re referring to an option provided by Chrome?
