### ISSUE TITLE
Docs wrongly highlighted as fixed issue with DuckDuckGo

### ISSUE THREAD

**Issue by normanlolx** [grasmash/drupal-issue-chrome#6]
https://duckduckgo.com/?q=drupal+8+custom+page&atb=v166-1&ia=web
![Screenshot 2019-06-14 13 00 28](https://user-images.githubusercontent.com/3585653/59505055-a1b0a580-8ea4-11e9-962a-dc07bae2b04b.png)

https://www.google.com/search?q=drupal+8+custom+page
![Screenshot 2019-06-14 13 00 49](https://user-images.githubusercontent.com/3585653/59505072-aaa17700-8ea4-11e9-9f7c-eeb2b2ba8126.png)

macOS Mojave 10.14.5
Chrome Version 75.0.3770.51 (Official Build) beta (64-bit)
Drupal Issue Chrome Version 0.0.4

**Comment by grasmash** [comment]
This is already fixed in 0.0.5, which is in queue to be published, thanks!

**Comment by grasmash** [comment]
Released. Thanks!
